### ISSUE TITLE
Issue with Ruby 3.1.5

### ISSUE THREAD

**Issue by rdimartino** [ruby-syntax-tree/syntax_tree#455]
I noticed this from the test failures on [this PR](https://github.com/prettier/plugin-ruby/pull/1433)

There's different behavior between Ruby 3.1.4 and 3.1.5

Ruby 3.1.4
```
❯ rbenv shell 3.1.4
❯ bundle exec stree format -e 'foo::x = 1'
foo.x = 1
❯ bundle exec stree ast -e 'foo::x = 1'
(program (statements ((assign (field (vcall (ident "foo")) :"::" (ident "x")) (int "1")))))
```

Ruby 3.1.5
```
❯ rbenv shell 3.1.5
❯ bundle exec stree format -e 'foo::x = 1'
undefined method `comments' for 73:Integer

      operator == :"::" ? [] : operator.comments
                                       ^^^^^^^^^
❯ bundle exec stree ast -e 'foo::x = 1'   
(program (statements ((assign (field (vcall (ident "foo")) 73 (ident "x")) (int "1")))))
```

**Comment by kddnewton** [comment]
Reported here: https://bugs.ruby-lang.org/issues/20449. Looks like this is a bug in the Ruby 3.1.5 backport. I'll put a workaround in here.

**Comment by rdimartino** [comment]
Great, thanks! I found the offending commit and submitted a patch https://github.com/ruby/ruby/pull/10610

I've never used the Ruby bug tracker before. Is there something that I should do there too?

**Comment by kddnewton** [comment]
Yeah if you want to comment on the redmine ticket if you want with the PR but I can do it as well if you don't want to make an account.

**Comment by kddnewton** [comment]
Fixed on main
